stages:
  - build
  - deploy

build:
  stage: build
  image: node:alpine
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

deploy-dev:
  image: ruby:latest
  stage: deploy
  dependencies: 
    - build
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$DEVELOPMENT_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop

deploy-prod:
  image: ruby:latest
  stage: deploy
  dependencies: 
    - deploy-dev
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$PRODUCTION_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master
